server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances2
          uri: https://github.com/lucasmuar/microservicios-tut
          search-paths: config-data 
          skip-ssl-validation: true
      allowOverride: true          
  application:
    name: config-service
